# Generated by Django 5.2.7 on 2025-10-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Banner',
            field=models.ImageField(blank=True, default='default_img.png', upload_to=''),
        ),
    ]
