# Generated by Django 5.2.7 on 2025-10-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_id_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Banner',
            field=models.ImageField(blank=True, default='/blog/assets/imgs/toji.png', upload_to=''),
        ),
    ]
