# Generated by Django 5.2.7 on 2025-10-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Banner',
            field=models.ImageField(blank=True, default='toji.png', upload_to=''),
        ),
    ]
