# Generated by Django 5.2.7 on 2025-10-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Banner',
            field=models.ImageField(blank=True, default='/assets/imgs/toji.png', upload_to=''),
        ),
    ]
