# Generated by Django 5.2.7 on 2025-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Banner',
            field=models.ImageField(blank=True, default='toji.png', upload_to=''),
        ),
    ]
