# Generated by Django 5.2.7 on 2025-10-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
